### ISSUE TITLE
Error loading add-ons

### ISSUE THREAD

**Issue by mfarooqmoinuddin** [codespaces-io/akurath#4]
I am getting plug-in issue while loading in browser and it not showing the terminal option in akurath. Attached the screenshot. 
![akurath](https://user-images.githubusercontent.com/42200534/45081721-7333bc00-b115-11e8-9510-d676f48638ae.PNG)

**Comment by lloydmuv** [comment]
getting the same error here too - 
Sep 21 21:05:26 lab1.lloyd.co.zw dockerd-current[9874]: [log][hooks] use hook auth
Sep 21 21:05:26 lab1.lloyd.co.zw dockerd-current[9874]: [log][events] users.add : { userId: 'test@test.com',
Sep 21 21:05:26 lab1.lloyd.co.zw dockerd-current[9874]:   token: '5844o',
Sep 21 21:05:26 lab1.lloyd.co.zw dockerd-current[9874]:   name: 'test@test.com',
Sep 21 21:05:26 lab1.lloyd.co.zw dockerd-current[9874]:   email: 'test@test.com',
Sep 21 21:05:26 lab1.lloyd.co.zw dockerd-current[9874]:   mtime: 1537578326,
Sep 21 21:05:26 lab1.lloyd.co.zw dockerd-current[9874]:   settings: {} }
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]: [error][rpc] Error  Error: Command failed: fatal: Not a git repository (or any parent up to mount point /workspace)
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]: 
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]: Error: Error: Command failed: fatal: Not a git repository (or any parent up to mount point /workspace)
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]: 
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]:     at Object.module.exports.error (/usr/lib/node_modules/akurath/node_modules/gittle/lib/errors.js:5:17)
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]:     at /usr/lib/node_modules/akurath/node_modules/gittle/lib/git.js:92:49
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]:     at ChildProcess.exithandler (child_process.js:662:7)
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]:     at ChildProcess.emit (events.js:98:17)
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]:     at maybeClose (child_process.js:766:16)
Sep 21 21:05:29 lab1.lloyd.co.zw dockerd-current[9874]:     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
Sep 21 21:08:26 lab1.lloyd.co.zw dockerd-current[9874]: [log][reporting] report 1 events
Sep 21 21:08:26 lab1.lloyd.co.zw dockerd-current[9874]: [log][hooks] use hook events
Sep 21 21:10:01 lab1.lloyd.co.zw systemd[1]: Created slice User Slice of root.

**Comment by arkumar5420** [comment]
Hi - I', also seeing the same issue (error loading addons and no terminal seen) . Please suggest a solution

**Comment by f1l1pp0s** [comment]
I am also facing the same issue, with logs attached.
![error](https://user-images.githubusercontent.com/19852214/46660022-cf7b7700-cbbe-11e8-8327-52e5b814256a.GIF)

**Comment by scalzadonna** [comment]
I'm having the same issue (error loading addons and no terminal seen) , is this project still alive?
